version: '3.3'
# Single server setup for dev

services:
  legacyphpapache:
    build:
      context: ../../../
      dockerfile: external/ezp-toolkit/docker-ezpublishplatform/dockerfiles/legacy-phpapache/Dockerfile
#    image: ezsystems/legacy-apache
    volumes:
     - ${COMPOSE_DIR}/../../../:/var/www:cached
#     - ${COMPOSER_HOME}:/root/.composer:cached
     - $HOME/.ssh/id_rsa:/id_rsa
    depends_on:
     - db
    ports:
     - "8082:80"
    environment:
     - COMPOSER_MEMORY_LIMIT
#     - SYMFONY_ENV=${SYMFONY_ENV-dev}
#     - SYMFONY_DEBUG
#     - SYMFONY_HTTP_CACHE
#     - SYMFONY_TRUSTED_PROXIES
     - DATABASE_USER
     - DATABASE_PASSWORD
     - DATABASE_NAME
     - DATABASE_HOST=db
#     - RECOMMENDATIONS_CUSTOMER_ID
#     - RECOMMENDATIONS_LICENSE_KEY
#     - PUBLIC_SERVER_URI
#     - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
#     - FASTLY_SERVICE_ID
#     - FASTLY_KEY
#    networks:
#     - backend

