version: '3.3'

services:
    apache_modphp:
        image: ${COMPOSE_PROJECT_NAME}_apache_modphp
        build:
            context: ../../
            dockerfile: external/ezp-toolkit/ezplatform/Dockerfile-7.3-apache_modphp

        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - SYMFONY_ENV=${SYMFONY_ENV-dev}
            - SYMFONY_DEBUG
            - SYMFONY_HTTP_CACHE
            - SYMFONY_TRUSTED_PROXIES
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - FASTLY_SERVICE_ID
            - FASTLY_KEY
            - XDEBUG_CONFIG
        networks:
            - backend
        ports:
            - "8079:80"
#        command: /bin/bash -c "cd /var/www && cp doc/apache2/vhost.template doc/apache2/vhost_modphp.template && sed -i "s/SetHandler/#SetHandler/g" doc/apache2/vhost_modphp.template && bin/vhost.sh --template-file=doc/apache2/vhost_modphp.template > /etc/apache2/sites-available/000-default.conf && apache2-foreground"

    apache_phpfpm:
        build:
            context: ../../
            dockerfile: external/ezp-toolkit/ezplatform/Dockerfile-7.3-apache_phpfpm
            args:
                APACHE_IMAGE: ${COMPOSE_PROJECT_NAME}_apache_modphp

        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - SYMFONY_ENV=${SYMFONY_ENV-dev}
            - SYMFONY_DEBUG
            - SYMFONY_HTTP_CACHE
            - SYMFONY_TRUSTED_PROXIES
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - FASTLY_SERVICE_ID
            - FASTLY_KEY
            - XDEBUG_CONFIG
#            - FASTCGI_PASS=app:9000
            - FASTCGI_PASS=fcgi://app:9000
        networks:
            - backend
        ports:
            - "8078:80"
        # Remove "|fcgi://localhost/" part from SetHandler directive
        #command: /bin/bash -c "cd /var/www && cp doc/apache2/vhost.template doc/apache2/vhost_phpfpm.template && sed -i 's_|fcgi://localhost/__g' doc/apache2/vhost_phpfpm.template && bin/vhost.sh --template-file=doc/apache2/vhost_phpfpm.template > /etc/apache2/sites-available/000-default.conf && apache2-foreground"
