version: '3.3'

services:

    redisinsight:
        image: redislabs/redisinsight:latest
        networks:
            - backend
        ports:
            - "8001:8001"
        # If you need to to import an .rds, this mount will make that easier...
        #volumes:
            # - ${COMPOSE_DIR}/../..:/var/www
